version: "3"
services:
  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    restart: always
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  dbdata:
